language: node_js
cache: yarn
node_js:
- '6'
- '6.1'
after_success:
- npm run test:cover:travis
script:
- npm run build
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  region: us-west-2
  bucket: homelessness.civicpdx.org
  skip_cleanup: true
  local_dir: build
